In [63]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder,StandardScaler,LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score

In [4]:
df = pd.read_csv('data/WA_Fn-UseC_-Telco-Customer-Churn.xls')

In [5]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [7]:
df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].mean())

In [8]:
df.drop(columns=['customerID'],inplace=True)

In [38]:
X = df.drop(columns=['Churn'])
y = df['Churn']
X

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,Nophoneservice,DSL,No,Yes,No,No,No,No,Monthtomonth,Yes,Electroniccheck,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,Oneyear,No,Mailedcheck,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Monthtomonth,Yes,Mailedcheck,53.85,108.15
3,Male,0,No,No,45,No,Nophoneservice,DSL,Yes,No,Yes,Yes,No,No,Oneyear,No,Banktransfer(automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiberoptic,No,No,No,No,No,No,Monthtomonth,Yes,Electroniccheck,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,Oneyear,Yes,Mailedcheck,84.80,1990.50
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiberoptic,No,Yes,Yes,No,Yes,Yes,Oneyear,Yes,Creditcard(automatic),103.20,7362.90
7040,Female,0,Yes,Yes,11,No,Nophoneservice,DSL,Yes,No,No,No,No,No,Monthtomonth,Yes,Electroniccheck,29.60,346.45
7041,Male,1,Yes,No,4,Yes,Yes,Fiberoptic,No,No,No,No,No,No,Monthtomonth,Yes,Mailedcheck,74.40,306.60
7042,Male,0,No,No,66,Yes,No,Fiberoptic,Yes,No,Yes,Yes,Yes,Yes,Twoyear,Yes,Banktransfer(automatic),105.65,6844.50

In [29]:
numerical_feature = X.select_dtypes(exclude="str").columns
categorical_feature = X.select_dtypes(include="str").columns
categorical_feature

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str')

In [39]:
for col in categorical_feature:
    df[col] =  df[col].str.replace(' ', '')
    df[col] =  df[col].str.replace('-', '')

In [41]:
X.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,Nophoneservice,DSL,No,Yes,No,No,No,No,Monthtomonth,Yes,Electroniccheck,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,Oneyear,No,Mailedcheck,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Monthtomonth,Yes,Mailedcheck,53.85,108.15
3,Male,0,No,No,45,No,Nophoneservice,DSL,Yes,No,Yes,Yes,No,No,Oneyear,No,Banktransfer(automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiberoptic,No,No,No,No,No,No,Monthtomonth,Yes,Electroniccheck,70.70,151.65

In [42]:
preprocessor = ColumnTransformer([
    ('OHE',OneHotEncoder(drop='first'),categorical_feature),
    ('SC',StandardScaler(),numerical_feature)
])

In [66]:
le = LabelEncoder()

y = le.fit_transform(y)
y

array([0, 0, 1, ..., 0, 1, 0], shape=(7043,))

In [67]:
X = preprocessor.fit_transform(X)

ValueError: Specifying the columns using strings is only supported for dataframes.

In [68]:
X

array([[ 0.        ,  1.        ,  0.        , ..., -1.27744458,
        -1.16032292, -0.99497138],
       [ 1.        ,  0.        ,  0.        , ...,  0.06632742,
        -0.25962894, -0.17387565],
       [ 1.        ,  0.        ,  0.        , ..., -1.23672422,
        -0.36266036, -0.96039939],
       ...,
       [ 0.        ,  1.        ,  1.        , ..., -0.87024095,
        -1.1686319 , -0.85518222],
       [ 1.        ,  1.        ,  0.        , ..., -1.15528349,
         0.32033821, -0.87277729],
       [ 1.        ,  0.        ,  0.        , ...,  1.36937906,
         1.35896134,  2.01391739]], shape=(7043, 30))

In [69]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)
print(X_train)
print(y_train)

[[ 1.          1.          1.         ...  0.88073469  0.19736523
   0.65642602]
 [ 1.          0.          0.         ... -1.27744458  0.52473924
  -0.97258569]
 [ 1.          0.          0.         ... -0.78880022 -1.51096208
  -0.89350724]
 ...
 [ 1.          1.          1.         ... -0.82952058 -1.44947559
  -0.87302013]
 [ 1.          0.          0.         ... -0.82952058  1.15289851
  -0.47824601]
 [ 1.          0.          0.         ... -0.25943549 -1.49434411
  -0.80623836]]
[0 0 0 ... 0 1 0]

In [70]:
model = LogisticRegression(class_weight='balanced')

In [71]:
model.fit(X_train,y_train)

LogisticRegression(class_weight='balanced')

In [72]:
y_train_pred = model.predict(X_train)

In [73]:
y_test_pred = model.predict(X_test)
y_test_pred

array([1, 0, 0, ..., 0, 1, 0], shape=(2113,))

In [75]:
print(f'f1 score for train data : {f1_score(y_train,y_train_pred)*100}')
print(f'f1 score for test data : {f1_score(y_test,y_test_pred)*100}')

f1 score for train data : 61.73059768064228
f1 score for test data : 65.12890094979647